In [3]:
import urllib.request
import zipfile
import os
import ssl

try:
    os.mkdir("files")
except:
    pass

ssl._create_default_https_context = ssl._create_unverified_context

with urllib.request.urlopen('https://courses.cs.tau.ac.il/pyProg/2425a/resources/notebook_resources.zip') as f:
    content = f.read()

with open('files/notebook_resources.zip', 'wb') as f:
    f.write(content)

with zipfile.ZipFile('files/notebook_resources.zip', 'r') as zip_ref:
    zip_ref.extractall('files')

print(os.listdir('files'))

import pandas as pd
pd.options.display.max_rows=5

['baby.png', 'countries-of-the-world.csv', 'dialation.png', 'dialation_2.png', 'dog.png', 'dog_noised.png', 'erosion.png', 'erosion_2.png', 'evil_morty_1.png', 'evil_morty_change.png', 'evil_morty_change_3.png', 'evil_morty_change_noised.png', 'evil_morty_segmentation.png', 'ex1.csv', 'ex2.csv', 'koala.png', 'notebook_resources.zip', 'orders_2_2024.csv', 'orders_3_2024.csv', 'orders_4_2024.csv', 'products2.csv', 'ship.png', 'StudentsGrades.csv', 'witcher_1.csv', 'witcher_2.csv', 'woman_noised.png', '__MACOSX']

# גישה בסיסית לטבלה

נתחיל מטעינת טבלת הציונים שלנו מהקובץ files/StudentsGrades.csv לתוך `df`:

In [4]:
inputFileName = "files/StudentsGrades.csv"
df = pd.read_csv(inputFileName)
display(df)

,Name,Programming,Marine Biology,Stellar Cartography,Math,History,Planet Survival,Art
0,Yael,50,56,70,60,87,65,91
1,Nadav,61,77,75,75,63,52,88
...,...,...,...,...,...,...,...,...
11,Tom,98,76,98,100,98,92,80
12,Adi,76,87,34,90,88,84,70

לפני שנתחיל לנתח את הנתונים של הטבלה, ייתכן כי נרצה לדעת עליה כמה נתונים כללים את הטבלה.

נניח כי נרצה להחזיר את מספר השורות בטבלה. נוכל לעשות זאת באמצעות פונקציה שכבר הזכרנו בעבר: `len`:

In [5]:
print(len(df))

13

מה לגבי מספר העמודות?   
מסתבר שיש שדה מיוחדת ב`DataFrame` הנקראת `shape`, והיא מחזירה גם את מספר השורות וגם את מספר בעמודות כ`tuple`:

In [6]:
print(df.shape)

(13, 8)

כפי שהזכרנו ביחידה הקודמת, לכל עמודה יש טיפוס משלה. כדי לקבל את הטיפוס של כל עמודה ניתן להשתמש בשדה `dtypes`

In [7]:
print(df.dtypes)

Name               object
Programming         int64
                    ...
Planet Survival     int64
Art                 int64
Length: 8, dtype: object

```{admonition} **שימו לב**
:class: warning

עמודות מחרוזת (כמו Name בדוגמא לעיל) מיוצגות בPandas ע"י הטיפוס `object` 
```

### גישה לערכים בטבלאות וסדרות: `[]`, `iloc[,]` ו-`loc[,]`

ב-Pandas קיימות מספר דרכים לגשת לנתונים מטבלה. השיטה הפשוטה ביותר היא `df[x]`, שמחזירה עמודה לפי השם שלה. אם נפעיל את `[]` על סדרה (`Series`), לדוגמא, `s[x]`,  נקבל ערך שנמצא בתא בשם `x`.   

בנוסף, קיימות שתי מתודות מאוד שימושיות: `df.loc[x,y]` שמבוססת על **שמות** השורות (`x`) ועמודות (`y`), ו־`df.iloc[x,y]` שמבוססת על **המיקומי** של השורות והעמודות (`x` ו-`y`) בהתאמה.   
באמצעות מתודות אלו, ניתן לבצע חיתוך על השורות והעמודות יחדיו בתוך הסוגריים המרובעים.

`df[x]`

`s[x]`

`df.loc[x,y]`

`df.iloc[x,y]`

בכל אחת  מהאופציות הללו, `x` יכול לייצג עבור טבלה:


- שורה בודדת
- Slicing של שמות/מיקומי שורות
- רשימה של שמות/מיקומי שורות.

באופן דומה ניתן לגשת לעמודת או מספר עמודות באמצעות `y`.   

**חשוב להבחין בין שלושת הדרכים הללו, משום שכל אחת מהן מתנהגת אחרת**.

```{admonition} **שימו לב**
:class: warning

בניגוד לסדרות מספריות כפי שראינו עד כה בקורס, Slicing לפי שמות (ב`[]` ו-`loc[]`) רץ מהשם בראשון **כולל* עד השם האחרון **כולל**, לפי סדר הופעת השורות/העמודות.  

שימוש בSlicing ב`iloc[]` מתנהג כפי שראינו עד כה בSlicing: כלומר, רץ מהמספר הראשון **כולל** עד האחרון **לא כולל**

```


כאשר ניגשים לערכים בטבלה, סוג האובייקט שניגשים אליו תלוי בכמות השורות והעמודות שנבחרו: 
- גישה לתא יחיד מחזירה ערך בודד בהתאם לטיפוס הנתונים של העמודה.
- גישה לעמודה אחת או שורה אחת מחזירה אובייקט מסוג `Series`, שהוא וקטור חד-ממדי.  
- גישה למספר עמודות ומספר שורות, התוצאה היא `DataFrame`, כלומר טבלה דו-ממדית.

למטה מופיעות מספר דוגמאות. ודאו שאתה מבינים מדוע מתקבלים הערכים המודפסים.

#### חילוץ ערכים מטבלה

In [8]:
df_first3=df.iloc[0:3,0:3]
print(type(df_first3))
display(df_first3)

<class 'pandas.core.frame.DataFrame'>

     Name  Programming  Marine Biology
0    Yael           50              56
1   Nadav           61              77
2  Michal           81              72

In [19]:
s = df.iloc[0]
print(type(s))
print(s)

<class 'pandas.core.series.Series'>
Name               Yael
Programming          50
                   ...
Planet Survival      65
Art                  91
Name: 0, Length: 8, dtype: object

In [20]:
print(df.iloc[:,0])

0      Yael
1     Nadav
      ...
11      Tom
12      Adi
Name: Name, Length: 13, dtype: object

#### חילוץ ערכים מסדרה

In [10]:
df_first1=df.iloc[0,0:3]
print(type(df_first1))
display(df_first1)

<class 'pandas.core.series.Series'>

Name              Yael
Programming         50
Marine Biology      56
Name: 0, dtype: object

In [12]:
print(df_first1.iloc[0])

Yael

In [13]:
print(df_first1.iloc[:,0])

IndexingError: Too many indexers

### תרגול: `iloc`  vs. `loc`

נראה כעת שלוש דרכים לחלץ את השורה הראשונה, השלישית והחמישית מתוך `df`:

In [43]:
display(df.iloc[[0,2,4]])

,Name,Programming,Marine Biology,Stellar Cartography,Math,History,Planet Survival,Art
0,Yael,50,56,70,60,87,65,91
2,Michal,81,72,76,94,67,81,78
4,Danielle,36,74,82,40,78,86,65

In [45]:
display(df.iloc[0:5:2])

,Name,Programming,Marine Biology,Stellar Cartography,Math,History,Planet Survival,Art
0,Yael,50,56,70,60,87,65,91
2,Michal,81,72,76,94,67,81,78
4,Danielle,36,74,82,40,78,86,65

In [49]:
display(df.loc[0:4:2])

,Name,Programming,Marine Biology,Stellar Cartography,Math,History,Planet Survival,Art
0,Yael,50,56,70,60,87,65,91
2,Michal,81,72,76,94,67,81,78
4,Danielle,36,74,82,40,78,86,65

שימו לב שבגלל שבדוגמא האחרונה אנו משתמשים ב`loc` ולכן הגדרנו את הטווח עד `4` ולא `5`.    
אם היינו מנסים להפעיל אותו Slicing על iloc, לא היינו מקבלים את הערך החמישי:

In [51]:
display(df.iloc[0:4:2])

,Name,Programming,Marine Biology,Stellar Cartography,Math,History,Planet Survival,Art
0,Yael,50,56,70,60,87,65,91
2,Michal,81,72,76,94,67,81,78

1. נסו כעת בעצמכם לחלץ מהטבלה `df` את ארבעת השורות האחרונות בכל אחת השלושת השיטות שהדגמנו למעלה **תוך שימוש באינקסים שליליים**

In [ ]:
# Write your code here

2. בשורה להלן בוצע ניסון לחלץ את השורה האחרונה מהטבלה

In [ ]:
print(df.loc[-1])

מדוע התגבלה שגיאה?

```{admonition} **פתרון**
:class: dropdown, tip

המתודה `loc` ניגשת לשורות לפי השמות שלהן. על מנת לגשת לפי מיקום (-1), יש להשתמש ב`iloc`
```

### שמות שורות ועמודות בטבלאות וסדרות

ב-DataFrame שמות השורות ושמות העמודות נשמרים בשדות ייעודיים: 
 - שמות השורות נשמרים בשדה `index`
 - שמות העמודות נשמרים במאפיין `columns`
 
שני השדות הם מסוג המחלקה **Index**, שניתן לראות בה מחלקה כללית לייצוג שמות.

שמות התאים בתוך `Series` נקראים גם הם `index`, ללא קשר אם ה-`Series` מייצגת מעמודה או משורה.   
זכרו כי `Series` היא **חד-מימדית** בעוד הקונספט של שורה ועמודה נגזר מכך קיים רק בהקשר של `DataFrame` - באיך שה-`Series` ממקום בו (בדומה לשורה או עמודה בודדת במטריצה).

In [60]:
s=df.loc[0]
print(type(s))
print(s.index)

<class 'pandas.core.series.Series'>
Index(['Name', 'Programming', 'Marine Biology', 'Stellar Cartography', 'Math',
       'History', 'Planet Survival', 'Art'],
      dtype='object')

לסדרה גם יכול להיות שם, השמור בשדה `name`. אם הסדרה נגזרה משורה/עמודה בטבלה, הערך של `name`יהיה שם השורה או העמודה כפי שהופיע במקור בטבלה:

In [61]:
print(s.name)

0